### ISSUE TITLE
Dealing with additional atlas resolutions

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainatlas-api#16]
Currently, atlases are only defined at original resolutions (i.e. 10, 25 & 50um for the ARA and 125um for the Swanson rat atlas). I would like to support additional resolutions, e.g.:
* I use a 100um ARA for automated testing and troubleshooting (anything bigger takes too long to register on 1/2 CPU cores)
* I only have [this atlas from the Kim lab](https://www.nature.com/articles/s41467-019-13057-w) at one resolution, and would like to support lower resolutions (a number of users have asked for lower resolutions, because they don't need them, and would rather quicker registration using less RAM).

I'm not sure exactly how to deal with this. Maybe:
* For the ARA, we could generate the 100um atlas by just downsampling the 50um atlas from the API.
* For the Kim atlas, which is defined in ARA coordinate space, I was planning on using the 10um annotations image file I have, and then combining it with the 10um template downloaded from the API. The other resolutions could be supported by downsampling the annotations file and combining with the 25um or 50um atlas downloaded from the Allen.
* Any other atlas without an API could just be downsampled normally.

**Comment by FedeClaudi** [comment]
Yeah sounds good, I don't mind having extra atlases/resolutions. 

How slow is the downsampling? Should we just host the high res version and implement the downsampling locally?

**Comment by adamltyson** [comment]
I'd like all resolutions to be hosted for testing and troubleshooting. If we need to download and then downsample the atlas, a lot of the amap & cellfinder tests would time out.

**Comment by FedeClaudi** [comment]
ok no prob

**Comment by vigji** [comment]
If we don't have urgent considerations on GIN space - which I don't think we have ATM - I would go for hosting multiple resolutions versions, making sure they are generated with the same scripts changing resolution only

**Comment by adamltyson** [comment]
> If we don't have urgent considerations on GIN space

This shouldn't be an issue, we're only ever going to be downsampling, so the space needed will be relatively small.

**Comment by vigji** [comment]
Related to this so I won't open another issue - the meshes should be generated all in the same measurement units - matching the resolution metadata specification, I would say in microns - although this might be weird for big things like human atlas. @FedeClaudi what do you think? What units are they currently in the human stack?

**Comment by FedeClaudi** [comment]
I'm not sure if microns is the best or if it can be specified on a per-atlas basis (which should be fine since you'd only be using one atlas at the time).

Either way, we can add code to `mesh_utils.extract_mesh_from_mask' to enforce a certain resolution (which ultimatly consists of multiplying each vertex's coordinates by some scalar factor no?)

**Comment by vigji** [comment]
It's just that ideally the user is never really exposed to the numbers and we don't care about that too much. But then I wonder if it affects file size and read speed - maybe yes, as they are saved as ascii?)...?

So my proposal:
 - if resolution does not change file size, we keep microns and forget about the problem;
 - If resolution does change significantly (>20%?) file size and reading speed, then let's add that as an option to be specified per-atlas.

**Comment by FedeClaudi** [comment]
we can check I guess. But given that all it changes is a constant factor for all vertices coordinates, you can save it in a more economical way and then multiply the values when loading, though that's not the best. 

Maybe it's worth having slightly larger files for the sake of consistency

**Comment by vigji** [comment]
Ok, I did a quick test and it does not change anything over 6 orders of magnitude as full floats are written anyway. So I would opt for consistency - the only place where this could come out is scalebar in visualisations, and that would be quick to automatically change.

**Comment by FedeClaudi** [comment]
okay, where how do we want to implement this?

**Comment by vigji** [comment]
So, I will make in half an hour another PR - finger crossed you won't kill me :p - that cleans up a bit more the saving part of the atlas generation so that all the files will be saved by the same function. So ideally the scripts will be loading/polishing the data, but all the *final* saving for all files is handled by a single function for all atlases - I am sure we must have this for consistency.

So in this schema you load you meshes, in the script you do the multiplication on the vertices to ensure they are in microns, and then you pass to the saving function some meshes objects (or even better, vertices-faces-edges tuple) with vertices in microns coordinates that will be saved.
